### ISSUE TITLE
Radio input is not getting updated inside Grid

### ISSUE THREAD

**Issue by sansantosh** [phil-r/react-native-grid-component#102]
Here is my Grid:

  <Grid style={styles.list}
            renderItem={this._renderItem}
            renderPlaceholder={this._renderPlaceholder}
            data={this.state.placeType}
            itemsPerRow={2}
          />

Here is my function to render checkbox:

  _renderItem = (data, i) => (
    <View style={[{ backgroundColor: data.color }, styles.item]} key={i} >
        <View style={{ height: 50 , width: 45, marginBottom: -12}}>
        <CheckBox
          color={"#000000"}
          selectedColor={"#000000"}
          checked={data.checked}
          checkedColor="black"
          onPress={() => {this.updateSelectedPlaceType(data.idx)}}
        />
      </View>
      <Text style={{color:'white'}}>{data.type}</Text>
    </View>
  );

And i have:
  updateSelectedPlaceType = (i) => {
    const newPlaceType = [...this.state.placeType];
    newPlaceType[i].checked = !newPlaceType[i].checked;
    this.setState({placeType : newPlaceType });
  }

**Comment by phil-r** [comment]
Close for inactivity
....
Mine mostly :trollface:
