### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by ameyk-gdb** [phil-r/react-native-grid-component#14]
I used your example on android but got error.
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

What could be the reason?

import React, { Component } from 'react';
import {
  StyleSheet,
  View,
} from 'react-native';

import Grid from 'react-native-grid-component';

export default class TimeScreen extends Component{

constructor(props) {
    super(props);

    this.state = {
      data: generateRandomColorsArray(21),
    };
  }

  _renderItem = (data, i) =>
    <View style={[{ backgroundColor: data }, styles.item]} key={i} />

  render() {
    return (
      <Grid
        style={styles.list}
        renderItem={this._renderItem}
        data={this.state.data}
        itemsPerRow={2}
        itemHasChanged={(d1, d2) => d1 !== d2}
        onEndReached={() =>
          this.setState({ data: [...this.state.data, ...generateRandomColorsArray(21)] })}
      />
    );
  }
}

const styles = StyleSheet.create({
  item: {
    flex: 1,
    height: 160,
    margin: 1,
  },
  list: {
    flex: 1,
  },
});

// Helper functions
// thanks materialuicolors.co
const colors = [
  '#F44336', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5',
  '#2196F3', '#03A9F4', '#00BCD4', '#009688', '#4CAF50',
  '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800',
  '#FF5722', '#795548', '#9E9E9E', '#607D8B',
];

function generateRandomColorsArray(length) {
  return Array.from(Array(length)).map(() => colors[Math.floor(Math.random() * colors.length)]);
}

**Comment by BigPun86** [comment]
+1
Can´t use 'react-native-grid-component' for my android app.

Environment: 

 "native-base": "^2.0.12",
    "react": "~15.4.1",
    "react-native": "0.42.0",
    "react-native-easy-grid": "^0.1.8",
    "react-native-grid-component": "^1.0.4",
    "react-native-navigation": "^2.0.0-experimental.238"

**Comment by faogustavo** [comment]
+1 @phil-r

**Comment by phil-r** [comment]
Sorry, I'm cleaning up issues and will close this one, you can re-open it if you wish.
