### ISSUE TITLE
Warning: Failed prop type: Invalid prop `refreshControl` of type `function` supplied to `ListView`, expected a single ReactElement.

### ISSUE THREAD

**Issue by cynhard** [phil-r/react-native-grid-component#18]
I use rn 0.42, encounter a problem with `Warning: Failed prop type: Invalid prop `refreshControl` of type `function` supplied to `ListView`, expected a single ReactElement.`

**Comment by phil-r** [comment]
Thanks for noticing, I close it as a duplicate of #13
