### ISSUE TITLE
onScroll event handler

### ISSUE THREAD

**Issue by eliasturbay** [phil-r/react-native-grid-component#20]
Hi @phil-r !
Is it possible to do something like this:
```
          onScroll={Animated.event([
            { nativeEvent: { contentOffset: { y: this.state.scrollY } } },
          ])}
```
???

or it isn't supported unless you make some changes to expose the `onScroll` event.

Thanks!

**Comment by phil-r** [comment]
Sorry, I'm cleaning up issues and will close this one, you can re-open it if you wish.
