### ISSUE TITLE
toggling the items per row doesn't work as excepted 

### ISSUE THREAD

**Issue by ericlewis** [phil-r/react-native-grid-component#22]
when I set the state I expect the items per row to reflect what I chose, what actually happens is I have to click the buttons numerous times and it doesn't match up.

`import React, { Component } from 'react';
import {
	Image,
	View,
	Text,
	Button,
	ScrollView,
	StyleSheet,
} from 'react-native';
import Collection from 'react-native-grid-component';
import { Col, Grid } from 'react-native-easy-grid';
import Icon from 'react-native-vector-icons/FontAwesome';

class Home extends Component {
	constructor() {
		super();
		this.state = {
			itemsPerRow: 2,
		};
	}

	static navigationOptions = ({ navigation }) => {
		return {
			headerTitle: (
				<View style={{ alignItems: 'center' }}>
					<Text style={{ color: 'white' }}>All Jeeps</Text>
					<Text style={{ color: 'white' }}>Viewing 75 Products</Text>
				</View>
			),
		};
	};

	_renderItem = (data, i) =>
		<View
			style={[
				{
					backgroundColor: '#E8E8D0',
				},
				styles.item,
			]}
			key={i}>
			<View />
			<Image
				style={{ width: 178, height: 200 }}
				source={{
					uri: data.image,
				}}
			/>
			<View
				style={{
					position: 'absolute',
					bottom: 0,
					left: 0,
					right: 0,
					padding: 10,
					backgroundColor: 'white',
				}}>
				<Text style={{ color: 'grey' }}>Jeep</Text>
				<Text style={{ color: '#A34C39' }}>
					item {data.title}
				</Text>
			</View>
		</View>;

	render() {
		return (
			<View style={styles.container}>
				<View
					style={{
						backgroundColor: '#A34C39',
						height: 44,
						flexDirection: 'row',
						alignItems: 'center',
						justifyContent: 'center',
					}}>
					<Button
						title="grid"
						onPress={() => this.setState({ itemsPerRow: 2 })}
					/>
					<Button
						title="list"
						onPress={() => this.setState({ itemsPerRow: 1 })}
					/>
				</View>
				<ScrollView>
					<Grid style={{ height: 20, alignItems: 'center', margin: 15 }}>
						<Col size={95}>
							<Text style={{ color: 'white' }}>Search area</Text>
						</Col>
						<Col size={5}>
							<Icon name="sliders" size={20} color="white" />
						</Col>
					</Grid>
					<Collection
						style={styles.list}
						renderItem={this._renderItem}
						data={[
							{
								title: 'MORE ARB twin compressor mount',
								image:
									'https://shechive.files.wordpress.com/2012/02/a-kitty-cat-7.jpg',
							},
							{
								title: 'Synergy bar pin eliminators',
								image: 'https://i.ytimg.com/vi/OAUtiqYDhEc/maxresdefault.jpg',
							},
							{
								title: 'Wii Controller',
								image:
									'https://www.softpaws.com/template/images/landing_page/july_cat_image.jpg',
							},
							{
								title: 'Super fantastic brakes',
								image:
									'https://pbs.twimg.com/profile_images/816329825438797824/a0PtxNhf.jpg',
							},
							{
								title: 'Buy this or you will die, or dont cause whatever',
								image: 'https://i.ytimg.com/vi/-HE3jj5Ah2M/maxresdefault.jpg',
							},
							{
								title: 'Roll bars',
								image:
									'https://c1.staticflickr.com/9/8195/8134328246_ff817faa2a_z.jpg',
							},
						]}
						itemsPerRow={this.state.itemsPerRow}
					/>
				</ScrollView>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#303747',
	},
	item: {
		flex: 1,
		height: 200,
		margin: 5,
		alignItems: 'center',
		justifyContent: 'center',
	},
	list: {
		flex: 1,
	},
});

export default Home;
`

**Comment by phil-r** [comment]
Sorry, I'm cleaning up issues and will close this one, you can re-open it if you wish.
