### ISSUE TITLE
Grid dont call renderItem when state change 

### ISSUE THREAD

**Issue by khalidahmada** [phil-r/react-native-grid-component#3]
I have data Array:

```
this.state = {social :  [ {name : 'facebook', status : false },{name : 'twitter', status : true },{name : 'linkedin', status : true }]
}
```

When i update array with setState() and i update status of some Item nothing rendred !

**Comment by phil-r** [comment]
Hi @khalidahmada can you send me a full example? I've just tested and everything works fine for me.

**Comment by phil-r** [comment]
Ok, I'll close it
