### ISSUE TITLE
itemHasChanged

### ISSUE THREAD

**Issue by khalidahmada** [phil-r/react-native-grid-component#4]
When i use itemHasChanged to resole the issue ( [#3](https://github.com/phil-r/react-native-grid-component/issues/3) ) of not update on staus change i use 

```
                    itemHasChanged = {(d1, d2) => {
                        return d1 === d2
                    }}
```

Is this normal ?

**Comment by phil-r** [comment]
Hello @khalidahmada that depends on what your items are. 
generally you do something like 
```js
itemHasChanged={ (d1, d2) => d1 !== d2 }
```
By the way it's the default value of `itemHasChanged`: https://github.com/phil-r/react-native-grid-component/blob/master/index.js#L42
Aslo if you have objects - this won't work. You'll need to write a custom comparison function or use something like `deepEqual`

**Comment by khalidahmada** [comment]
Thank You @phil-r :-D

**Comment by phil-r** [comment]
No problem @khalidahmada ;)
