### ISSUE TITLE
Moving to FlatList?

### ISSUE THREAD

**Issue by alvinmatias69** [phil-r/react-native-grid-component#85]
As we all know ListView is deprecated and has poorer performance than FlatList ([source](https://facebook.github.io/react-native/blog/2017/03/13/better-list-views)).
Do you have any plans to rewrite this using FlatList?

**Comment by phil-r** [comment]
Sure, sadly I don't work on react native projects right now, so it's a bit hard for me to be up to date 😞

**Comment by alvinmatias69** [comment]
Aw, that's too bad 😞
Well, I'll create a PR on this, what do you think?

**Comment by phil-r** [comment]
Sure! That would be amazing!

**Comment by phil-r** [comment]
can be tested using `npm i react-native-grid-component@next`
