### ISSUE TITLE
How to add a click event？

### ISSUE THREAD

**Issue by Swordce** [phil-r/react-native-grid-component#9]

**Comment by phil-r** [comment]
Hello @Swordce 

I think you're asking about how to add a "click" event to the grid item. 
To do that you just need to render an item, that can handle clicks, [Touchable highlight](https://facebook.github.io/react-native/docs/touchablehighlight.html) for example and use `onPress` property to provide a function that will be executed on "click".
 
```js
class Simple extends Component {

  _renderItem = (data, i) => (
     <TouchableHighlight onPress={() => console.log(data)}>
       <View style={[{backgroundColor: data}, styles.item]} key={i}/>
    </TouchableHighlight>
  )

  render() {
    return (
      <Grid
        style={styles.list}
        renderItem={this._renderItem}
        data={['black', 'white', 'red', 'green', 'blue']}
        itemsPerRow={2}
      />
    );
  }
}

```


I haven't tested the code above, but it should give you an idea.
